development:
  uri: mongodb://localhost:27017/uppic

test:
  uri: mongodb://localhost:27017/uppic

# set these environment variables on your prod server
production:
  uri: mongodb://localhost:27017/uppic

  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
